### ISSUE TITLE
Add buffer control

### ISSUE THREAD

**Issue by pepibumur** [pepibumur/PopcornTimeTV#4]
AppleTV limits the size of files that can be stored to 200 Mb. This limits how we're currently saving and consuming the movies. I propose the following:

Together with the download, implement an buffer control that knows about:
- The download status
- The playing status
- The file size

And with all these three sources try to control the file size, removing bytes that are not needed anymore if they have already been reproduced. That way we keep always the size under 200 Mb.

**Comment by diogoviannaaraujo** [comment]
Hey, what I got when reading here (https://developer.apple.com/library/tvos/documentation/General/Conceptual/AppleTV_PG/) was that the submitted app cant be more than 200mb in size, but the purgeable data can be bigger than that, the system will delete when out of space but that shouldnt be a problem because he cant do that with the app running.

**Comment by diogoviannaaraujo** [comment]
The text that says so:
> Your app can download the data it needs into its cache directory. Downloaded data is not deleted while the app is running. However, when space is low and your app is not running, this data may be deleted. Do not use the entire cache space as this can cause unpredictable results.

Some other places talking about the topic:

- https://forums.developer.apple.com/thread/19002
- https://forums.developer.apple.com/thread/19174

But i could not find about any size limit for this cache.

**Comment by pepibumur** [comment]
That's great @diogoviannaaraujo , do you have a real device? It would be gret if we could try with a movie and try to watch it from the beginning to the end.

Thanks for everything :stuck_out_tongue:

**Comment by JakeRound** [comment]
I loaded a previous push onto my device, watched the movie sicario which you implemented (Good movie btw). Movie initially loaded the stream for about 45 seconds after that the movie played without any buffering. Allowed me to pause and resume without any problems.

**Comment by diogoviannaaraujo** [comment]
I Have some devices, but for the apple tv I dont have any usb c cable yet, this things are hard to find here in Brazil. Should it work on the simulator? Maybe i should try with another magnet, or maybe i just screw when installing the dependencies.

**Comment by pepibumur** [comment]
It works with the simulator but I wanted to validate with a real device. It would be great if we could try on one :stuck_out_tongue:

**Comment by JakeRound** [comment]
Playback on device is fine, no issues apart from the movie will never start again if the app is quit and reopened.

**Comment by pepibumur** [comment]
:clap: :clap: that's a awesome new!, we can improve the reproduction to avoid it reaching the end of the file but at least we can get it working :P
